<a href="https://colab.research.google.com/github/sONg20NOW/25-1-winter-NLP-intern/blob/main/25_1_NLP_intern.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 01. [기초] - 딥 러닝을 시작하기 전에


nltk 설치

In [ ]:
# pip install nltk

In [ ]:
import nltk
nltk.__version__

'3.9.1'

nltk data 추가 설치

In [ ]:
# nltk.download()

KoNLPy 설치


In [ ]:
# pip install konlpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 57.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 493.8/493.8 kB 28.4 MB/s eta 0:00:00


In [ ]:
import konlpy
konlpy.__version__

'0.6.0'

Pandas, Numpy, Matplotlib 설치

In [ ]:
# pip install pandas

In [ ]:
# pip install numpy

In [ ]:
# pip install matplotlib

### Pandas 사용법
1. Series: 1차원 배열
2. DataFrame: 2차원 리스트

엑셀과 같은 외부 데이터를 읽어올 수도 있다

In [ ]:
import pandas as pd

### Numpy 사용법
1. t.ndim : t의 차원
2. t.shape: t의 크기

나머지는 컴비개에서 해봤으니 생략...

In [ ]:
import numpy as np

### Matplotlib 사용법
데이터를 차트나 플롯으로 시각화
1. plt.title() : 표 제목
2. plt.plot([x 값들], [y 값들]) : 그래프 그리기
3. plt.xlabel() : 축 이름 삽입
4. plt.legend() : 각 선이 어떤 데이터를 나타내는지
5. plt.show() : 차트 그리기

In [ ]:
import matplotlib as mpl

## 02. [기초] - 파이토치 기초(PyTorch Basic)


### PyTorch 사용법


#### 5) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요!


In [ ]:
import torch

t = np.array([
    [
        [0, 1, 2],
        [3, 4, 5]
    ],
    [
        [6, 7, 8],
        [9, 10, 11]
    ]
])

ft = torch.FloatTensor(t)

In [ ]:
print(ft.shape)

torch.Size([2, 2, 3])


In [ ]:
print(ft.view(-1, 3))

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])


#### 7) 언스퀴즈(Unsqueeze) - 특정 위치에 1인 차원을 추가한다.


In [ ]:
ft = torch.FloatTensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [ ]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(1))


tensor([[0., 1., 2.]])
tensor([[0.],
        [1.],
        [2.]])


#### 8) 타입 캐스팅(Type Casting)


In [ ]:
print(ft)
ft = ft.int()
print(ft)

tensor([0., 1., 2.])
tensor([0, 1, 2], dtype=torch.int32)


#### 9) 연결하기(concatenate)


dim = 0 : 첫번째 차원(행)을 늘려라

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


dim = 1 : 두번째 차원(열)을 늘려라

In [ ]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


#### 10) 스택킹(Stacking)
concatenate와 비슷하지만 스택킹이 더 많은 연산을 포함하고 있다

In [ ]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
# above code is same as below
# print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


#### 12) In-place Operation (덮어쓰기 연산)
연산 뒤에 '_'을 붙이면 기존의 값을 덮어쓰기 한다

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력


tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### Python Class
클래스 = 붕어빵 틀
똑같은 기능을 하는 함수를 독립적으로 구현하려면

In [ ]:
class Calculator:
    def __init__(self): # 객체 생성 시 호출될 때 실행되는 초기화 함수. 이를 생성자라고 한다.
        self.result = 0

    def add(self, num): # 객체 생성 후 사용할 수 있는 함수.
        self.result += num
        return self.result


In [ ]:
cal1 = Calculator()
cal2 = Calculator()

In [ ]:
print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10


## 03. [ML 입문] - 머신 러닝 입문하기(Machine Learning Basics)


### 03-01 선형 회귀와 자동 미분(Linear Regression and Autograd)


#### 3. 비용 함수(Cost function)에 대한 이해
비용 함수 = 손실 함수 = 오차 함수 = 목적 함수

MSE(Mean Squared Error) : 오차의 제곱합에 대한 평균


#### 4. 옵티마이저 - 경사 하강법(Gradient Descent)
Optimizer = 손실 함수 최소화 하는 방법


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드(random seed)를 줍니다.
torch.manual_seed(1)

train dataset 생성

In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

W, b 초기화
* requires_grad=True : 이 변수는 학습을 통해 계속 값이 변경되는 변수이다...

In [ ]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True)
# 가중치 W를 출력
print(W)

b = torch.zeros(1, requires_grad=True)
print(b)


tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


가설 세우기


In [ ]:
hypothesis = x_train * W + b
print(hypothesis)


tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


비용 함수 선언

In [ ]:
# 앞서 배운 torch.mean으로 평균을 구한다.
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)


tensor(18.6667, grad_fn=<MeanBackward0>)


경사 하강법 구현

* SGD(Stochastic Gradient Descent) = GD의 일종  
모든 데이터의 기울기를 반영하는 GD와 달리 무작위 데이터 하나의 기울기만 반영하여 GD 수행
* lr = learning rate




In [ ]:
optimizer = optim.SGD([W, b], lr=0.01)

